# -*- coding: utf-8 -*-
"""Aula 02 - desafio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoQfLX-Q-pOIjO4YVNVAcIwK61pagUft
"""

print("==Desafio Aula 02==")
temperatura = float(input("\nTemperatura (°C): "))
pressao_sistolica = int(input("Pressão Sistólica (mmHg): "))
nivel_dor = int(input("Nível de dor (0-10): "))

if temperatura > 39.5 or pressao_sistolica > 180 or nivel_dor >= 9:
  classe = "Vermelho"
elif temperatura > 38.5 or pressao_sistolica > 160 or nivel_dor >= 7:
  classe = "Laranja"
elif temperatura > 37.5 or pressao_sistolica > 140 or nivel_dor >= 4:
  classe = "Amarelo"
else:
  classe = "Verde"

print(f"\nTemperatura: {temperatura} °C, Pressão Sistólica: {pressao_sistolica} mmHg e Nível de dor: {nivel_dor}")

if classe == "Vermelho":
  resultado = "EMERGÊNCIA"
elif classe == "Laranja":
  resultado = "Muito urgente"
elif classe == "Amarelo":
  resultado = "Urgente"
else:
  resultado = "Pouco urgente"

print(f"Classificação: {classe} - {resultado}")

# "Escala de Dor - fonte:revistahupe.uerj.br"

if nivel_dor >= 7:
  print("Dor intensa !!!")
elif nivel_dor >= 4:
  print("Dor moderada !!")
elif nivel_dor >= 1:
  print("Dor leve !")
else:
  print("Sem dor")

