# -*- coding: utf-8 -*-
"""Aula 03 - desafio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h52r4BUrCsQfoqhOvQG8-i3S-DBaNAIu

# ***Desafio***
"""

print("\n===Relatório Final===")
vendas = [850, 1200, 980, 1560, 720, 1100, 890, 1340, 630, 1450, 970, 1280, 810, 1620, 750, 1050, 920, 1380, 660, 1490]
soma = 0
for valor in vendas:
  soma = valor + soma
print(f"Total vendido no mês: R${soma:.2f}")

contagem = 0
for elemento in vendas:
  contagem = contagem + 1
media = soma / contagem
print(f" A média diária: R${media:.2f} ")

maior_venda = vendas [0]
melhor_dia = 0
for i in range(len(vendas)):
  if vendas [i] > maior_venda:
      maior_venda = vendas[i]
      melhor_dia = i
print(f"Maior venda: R$ {maior_venda} feita no dia: {melhor_dia + 1}")

meta = 1000
dias_acima_meta = 0
for venda in vendas:
  if venda > meta:
    dias_acima_meta = dias_acima_meta + 1
print(f"Dias acima da meta: {dias_acima_meta} dias")

for i, venda in enumerate(vendas):
  if venda > 1500:
    print(f"Dia: {i}")
    break

  nova_meta = 1200
  tentativas = 0
  while True:
    palpite = float(input("Digite a nova meta: "))
    tentativas = tentativas + 1
    if palpite == 1200:
      print(f"Acertou ! {tentativas} tentativas")
      break
    else:
      print("Errou! Tente novamente...")