# -*- coding: utf-8 -*-
"""Aula 01- desafio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHyTKG6B7LbfCwolmGS-XxDOASxCnnwg
"""

nome   = input("Seu nome:")
qtda_item_1 = int(input("Quantidade do item_1 (unid): "))
valor_item_1 = float(input("Qual o valor do item_1: R$ "))
qtda_item_2 = int(input("Quantidade do item_2 (unid): "))
valor_item_2 = float(input("Qual o valor do item_2: R$ "))
qtda_item_3 = int(input("Quantidade do item_3 (unid): "))
valor_item_3 = float(input("Qual o valor do item_3: R$ "))

subtotal_1 = qtda_item_1 * valor_item_1
subtotal_2 = qtda_item_2 * valor_item_2
subtotal_3 = qtda_item_3 * valor_item_3

total = subtotal_1 + subtotal_2 + subtotal_3

desconto = 0

total_final = total - desconto


print(f"\nOlá, {nome}!")
print(f"Você comprou {qtda_item_1} unidades do item_1 por R$: {subtotal_1:.2f}.")
print(f"Você comprou {qtda_item_2} unidades do item_2 por R$: {subtotal_2:.2f}.")
print(f"Você comprou {qtda_item_3} unidades do item_3 por R$: {subtotal_3:.2f}.")
print(f"Sua compra custou: R$ {total:.2f}.")
print(f"Você ganhou um desconto de: R$ {desconto:.2f}.")
print(f"Você irá pagar: R$ {total_final:.2f}.")
print("\nOBRIGADA PELA PREFERÊNCIA, VOLTE SEMPRE!")

nome   = input("Seu nome:")
qtda_item_1 = int(input("Quantidade do item_1 (unid): "))
valor_item_1 = float(input("Qual o valor do item_1: R$ "))
qtda_item_2 = int(input("Quantidade do item_2 (unid): "))
valor_item_2 = float(input("Qual o valor do item_2: R$ "))
qtda_item_3 = int(input("Quantidade do item_3 (unid): "))
valor_item_3 = float(input("Qual o valor do item_3: R$ "))

subtotal_1 = qtda_item_1 * valor_item_1
subtotal_2 = qtda_item_2 * valor_item_2
subtotal_3 = qtda_item_3 * valor_item_3

total = subtotal_1 + subtotal_2 + subtotal_3

if total > 50:
  desconto = total * 0.10
else:
  desconto = 0

total_final = total - desconto


print(f"\nOlá, {nome}!")
print(f"Você comprou {qtda_item_1} unidades do item_1 por R$: {subtotal_1:.2f}.")
print(f"Você comprou {qtda_item_2} unidades do item_2 por R$: {subtotal_2:.2f}.")
print(f"Você comprou {qtda_item_3} unidades do item_3 por R$: {subtotal_3:.2f}.")
print(f"Sua compra custou: R$ {total:.2f}.")
print(f"Você ganhou um desconto de: R$ {desconto:.2f}.")
print(f"Você irá pagar: R$ {total_final:.2f}.")
print("\nOBRIGADA PELA PREFERÊNCIA, VOLTE SEMPRE!")

